server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mariadb://database-1.cbw22o8qwssf.ap-northeast-2.rds.amazonaws.com:3306/jwtdb?useSSL=false
    username: admin
    password: choe12345678
    driver-class-name: org.mariadb.jdbc.Driver



  jpa:
    hibernate:
      ddl-auto: create #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
